### ISSUE TITLE
Addition of TLS Certificate and Key to deployment as secrets 

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#128]
A secret is required by the ICAP Deployment. The certificate should have the configuration as per that example `kubectl` command below.

```
kubectl create secret tls icap-server-tls \ 
    --namespace icap-adaptation \ 
    --key tls.key  \ 
    --cert certificate.crt
```

`tls.key` and `certficate.crt` can be generated with the following command
```
openssl req -newkey rsa:2048 -nodes -keyout tls.key -x509 -days 365 -out certificate.crt
```

**Comment by mpigram** [comment]
Yes all sorted Paul - this is now part of the scripts and documentation
