### ISSUE TITLE
Request Processing Pod Submits archive-adaptation-request

### ISSUE THREAD

**Issue by tstepany** [filetrust/program-icap#134]

**Comment by NadHodeGW** [comment]
Tested all five archive types: 7z, rar, tar, tar.gz, zip
Icap response is 200 
The expected files appear in the transaction log
The processed files are available in the output archive (verified for zip)
The html report for a failed file processing is returned in the archive output as as html file (verified for zip)
![2021-02-09_14h09_44](https://user-images.githubusercontent.com/61200359/107376621-042ad080-6ae2-11eb-908a-ebb7c599f646.png)
