### ISSUE TITLE
Archive Processing Pod sends off adaptation requests in parallel

### ISSUE THREAD

**Issue by Diggers89** [filetrust/program-icap#152]

**Comment by NadHodeGW** [comment]
Tested all five archive types: 7z, rar, tar, tar.gz, zip
Icap response is 200 
The expected files appear in the transaction log
The processed files are available in the output archive 
The html report for a failed file processing is returned in the archive output as as html file 
![2021-02-09_14h09_44](https://user-images.githubusercontent.com/61200359/107383610-0e9c9880-6ae9-11eb-9e24-b9207dd9292d.png)
