### ISSUE TITLE
Mgt UI Request History reporting incorrect processing status

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#153]
Submitting a 'broken' file using the ICAP Client Test tool

**Expected Results**
File is blocked,
Request History shows file status as 'Blocked'

**Actual Results**

The processing logs indicate that the file is processed and an issue is found
![image (1)](https://user-images.githubusercontent.com/1354372/100123169-22cde380-2e72-11eb-83ef-266483f1a2a0.png)

But on the Mgt UI Request History page the document is marked 'Safe'.
![image (2)](https://user-images.githubusercontent.com/1354372/100123326-485aed00-2e72-11eb-8a0b-6c1730b8a642.png)

The submitted transaction events are
```
{
	"Events": [
		{
			"Properties": {
				"EventId": 16,
				"FileId": "7c4c7693-fa8c-45c6-a884-8389b6d6555f",
				"Mode": 1,
				"PolicyId": "00000000-0000-0000-0000-000000000000",
				"Timestamp": "2020-11-24T16:00:49.0877826Z"
			}
		},
		{
			"Properties": {
				"EventId": 32,
				"FileId": "7c4c7693-fa8c-45c6-a884-8389b6d6555f",
				"FileType": "Png",
				"Timestamp": "2020-11-24T16:00:49.0877826Z"
			}
		},
		{
			"Properties": {
				"EventId": 64,
				"FileId": "7c4c7693-fa8c-45c6-a884-8389b6d6555f",
				"Timestamp": "2020-11-24T16:00:49.0877826Z"
			}
		},
		{
			"Properties": {
				"Action": "replace",
				"EventId": 80,
				"FileId": "7c4c7693-fa8c-45c6-a884-8389b6d6555f",
				"Timestamp": "2020-11-24T16:00:49.0877826Z"
			}
		},
		{
			"Properties": {
				"EventId": 96,
				"FileId": "7c4c7693-fa8c-45c6-a884-8389b6d6555f",
				"GwOutcome": "replace",
				"Timestamp": "2020-11-24T16:00:49.0877826Z"
			}
		}
	]
}
```

**Comment by gw-sbirch** [comment]
![BrokenClean](https://user-images.githubusercontent.com/60774443/104189423-8ad08d00-5412-11eb-9516-24fe3f10ed0e.png)

@NadHodeGW please use this file to restest the issue.

**Comment by NadHodeGW** [comment]
Retested on icap-client-qa-main.uksouth.cloudapp.azure.com -p 1344
Submitted the attached broken file using the ICAP Client Test tool

Expected Results
The file is blocked,
Request History shows file status as 'Blocked'

Actual Results
The file is blocked,
Request History shows file status as 'Blocked by Policy'

[structuralIssues.xlsx](https://github.com/filetrust/program-icap/files/5803977/structuralIssues.xlsx)
