### ISSUE TITLE
Add endpoint logic to query azure file store

### ISSUE THREAD

**Issue by tstepany** [filetrust/program-icap#16]
Milestone: Brute Force

https://glasswall.atlassian.net/browse/FEATURE-656

Transaction Events: Transaction Events API - List endpoint
Add endpoint logic to query azure file store

**Comment by gw-sbirch** [comment]
Logic has been added that will search in parallel multiple file stores with the required filters.

**Comment by gw-sbirch** [comment]
see swagger page for usage

**Comment by gw-sbirch** [comment]
I have wrapped the two endpoints in an azure function app for use in testing without a kubernetes cluster
