### ISSUE TITLE
uk south cluster does not work on port 1344 with no tls

### ISSUE THREAD

**Issue by jpoolGW** [filetrust/program-icap#165]
**Endpoint:** icap-client-main.uksouth.cloudapp.azure.com & icap-client-main.northeurope.cloudapp.azure.com
**Repro Steps:**

- Send a file to the above endpoint using the gw_rebuild service on port 1344, with no tls
```    /usr/bin/c-icap-client -i icap-client-main.uksouth.cloudapp.azure.com -p 1345 -tls -tls-no-verify -s gw_rebuild -f /mnt/c/Validation/ICAP_Server/ResponseTimeTesting/TestFiles/jmxFileSet/cmw-r6-4.ppt -o /mnt/c/Validation/ICAP_Server/ResponseTimeTesting/Out/cmw-r6-4.ppt -v ```

**Expected result:** File is processed, out put file generated and correct response is returned
**Actual Result:** Connection to server takes a long time, File processing takes a long time, incorrect response message is returned

Additional info, the expected result occurs when sending requests on port 1345, with tls. See attached image for details
 
![2020-12-15_11h59_23](https://user-images.githubusercontent.com/60877176/102213005-fd128800-3ecd-11eb-9b24-ce0460cd55b6.png)

**Comment by NadHodeGW** [comment]
Closing this as is a duplicate and no longer replicated
