### ISSUE TITLE
Icap processing: the response code for a blocked file is 200 instead of 403

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/program-icap#166]
To replicate:

Set the routing option for Glasswall Blocked files to 'block'
Set the Adaptation policy for the file used to 'disallow'
Process the file through the icap server 

Command used: 
/usr/bin/c-icap-client -i icap-client-main.uksouth.cloudapp.azure.com -p 1345 -tls -tls-no-verify -s gw_rebuild  -f "/mnt/c/icap/tests/input/issues.docx" -o "/mnt/c/icap/tests/output/issues.docx" -v

UI endpoint: 
http://management-ui.uksouth.cloudapp.azure.com/policy

Expected:  
The respond code for the submitted file should be  403, the outcome in the UI should be Blocked by Policy & the html report received

Actual:
Although the outcome in the UI is Blocked by Policy & the html report received **but the respond code for the submitted file is 200**

![2021-01-04_17h38_04](https://user-images.githubusercontent.com/61200359/103564949-56f7e380-4eb7-11eb-82e2-7d4ae46a66cf.png)

**Comment by NadHodeGW** [comment]
This is not fixed, issue is still seen.

**Comment by BigPeeg** [comment]
Using the icap-clietn-develop.uksourth.cloudapp.azure.com endpoint to test.
Set Adaptation policy to block internal hyperlinks
![image](https://user-images.githubusercontent.com/1354372/105168010-6743cb80-5b11-11eb-8662-ed6e7c80efe9.png)
File Is Blocked
![image](https://user-images.githubusercontent.com/1354372/105168041-7296f700-5b11-11eb-8a44-a1baa236a8fa.png)
Correct Error Status is provided
![image](https://user-images.githubusercontent.com/1354372/105168062-7b87c880-5b11-11eb-879e-e037e41165cf.png)
Error report is supplied
![image](https://user-images.githubusercontent.com/1354372/105168101-880c2100-5b11-11eb-9392-5aafc1a5e06d.png)

**Comment by BigPeeg** [comment]
Changed were commited as v0.2 of the `mvp-icap-service` repo (SHA ee2702004492644a67e92c9bd37506e49386a053).
This commit was inserted into `icap-infrastructure` on 15th Jan (SHA 13cd10201809327b5e0bb39055121f6e7923982c), settings the `mvp-icap-service` tag to `main-ee27020`.

**Comment by NadHodeGW** [comment]
Retested after new changes applied to QA  

Fix is retested successfully
![image](https://user-images.githubusercontent.com/61200359/105224789-8d8b5a80-5b55-11eb-9c21-b38d372fd94e.png)
