### ISSUE TITLE
No dedicated QA instance of the Rancher deployed application exists

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#169]
QA need to have dedicated environments to perform functional testing against the application deployed on the production infrastructure.

It is expected that once the team following the deployment guide get success then we will get those instances, re-assess Monday & if not success then request Codurance manually deploy.

**Comment by tstepany** [comment]
I know it isnt bug but to have consistency with our QA spreadsheet,  I labeled it as bug.

**Comment by dpatel7** [comment]
Seen some issue Using Personal Account due to Quota, Reaching out to Abbas to get this move over to other subscription 
![image](https://user-images.githubusercontent.com/61416876/104707988-0b460500-5715-11eb-820c-92669fb895fe.png)

**Comment by tstepany** [comment]
QA got 9 clusters so this ticket can be closed, but getting new clusters will be on going
