### ISSUE TITLE
Incorrect data in Transaction Event Store causes empty Event History page

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#171]
Any problem in the reading of data from the transaction store stops the query returning anything at all!. Examples that have been found include
- Metadata.json empty
- Empty File ID Folder

Once a transaction has completed and resulted in incorrect data being recorded in the transaction store, all subsequent queries seem to be affected.

**Replication**
Currently, submitting an Archive File causes an empty FileID folder which will replicate the issue.

**Workaround**
Find the offending record in the Azure File Share and delete the transaction folder from the store.

**Comment by gw-sbirch** [comment]
@NadHodeGW this can be restested, invalid data will now be ignored.

**Comment by NadHodeGW** [comment]
Retested on icap-client-qa-main.uksouth.cloudapp.azure.com

Submitted few files which appear in the transaction log
Opened file id folder of one of them using the transaction id
Deleted the metadata.json
Uploaded an empty file named metadata.json

Result: the file no longer appears in the transaction log but all other transactions data are still available 
Any new processed transaction appears in the transaction log as expected
