### ISSUE TITLE
Scaling up the nodes on the Rancher cluster takes very long - estimated around 3.5 hr for 100 nodes

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/program-icap#172]

**Comment by dpatel7** [comment]
Today when i was scaling the cluster seen some nodes status become unhealthy once is reach 20 nodes Which is previously logged by Jamie . so i have removed those and incrementally scale up to 100 by doing 10 nodes each time and it took around 3.5 hours.

**Comment by dpatel7** [comment]
@tasssko Thanks for your hardwork.

Finally try to scale with 50 nodes. it took around 15 min to get all nodes to cluster. seen 1 node become unhealthy. rest of the nodes were stable.

**Comment by NadHodeGW** [comment]
Closing as @Jamie confirmed
