### ISSUE TITLE
Seen Janitor pods having issue pulling image while running in scale

### ISSUE THREAD

**Issue by dpatel7** [filetrust/program-icap#176]
We have seen janitor job failing to run. 
![image](https://user-images.githubusercontent.com/61416876/104323056-9d63c880-54dd-11eb-80c1-46ceccd4357d.png)
![image](https://user-images.githubusercontent.com/61416876/104323064-a05eb900-54dd-11eb-9cb4-d4aeba992f5d.png)

as per the Slack update from tass it was cause by the credentials have been revoked.

**Comment by dpatel7** [comment]
Credentials have changed and we are awaiting redeployment to restore service

**Comment by tstepany** [comment]
Dharam will close it.

**Comment by MattCavey** [comment]
@dpatel7 as agreed at the review - please close this.

**Comment by dpatel7** [comment]
The issue was due to changes in secret. is not seen again
