### ISSUE TITLE
Seen HTML report back from ICAP server saying "Document Access Blocked due to Policy"  when getting 403 Forbidden

### ISSUE THREAD

**Issue by dpatel7** [filetrust/program-icap#177]
Replica steps:

When cluster is non operational due to previously failing load test and we try and send single file request of any file type we are getting html report back saying "Document Access Blocked due to Policy" The error code: 9

step 1 - run command - /usr/bin/c-icap-client -i gw-icap-prd-nor.icap-proxy.curlywurly.me -tls -tls-no-verify -p 443 -s gw_rebuild -f /home/glasswall/input/test.png -o /home/glasswall/output/test1.png -v

step 2 - rename output file with html extension 
step 3 - open in browser

![image](https://user-images.githubusercontent.com/61416876/104324255-1e6f8f80-54df-11eb-9ad5-249a5c0c2e31.png)

![image](https://user-images.githubusercontent.com/61416876/104324213-0f88dd00-54df-11eb-8d8e-9925efaa14d2.png)

**Comment by dpatel7** [comment]
HTML Contain Updated bu Paul 
![image](https://user-images.githubusercontent.com/61416876/104707538-6cb9a400-5714-11eb-83c8-7c1cd1d70d00.png)

**Comment by BigPeeg** [comment]
Changes were committed as v0.2 of the mvp-icap-service repo (SHA ee2702004492644a67e92c9bd37506e49386a053).
This commit was inserted into icap-infrastructure on 15th Jan (SHA 13cd10201809327b5e0bb39055121f6e7923982c), settings the mvp-icap-service tag to main-ee27020.
