### ISSUE TITLE
Janitor pods pilling up In cluster after ImagePullBackOff issue 

### ISSUE THREAD

**Issue by dpatel7** [filetrust/program-icap#178]
I was on rancher UI and notice that the pod capacity was reach due to only 1 worker node. when I list all pods i have notice that Janitor pods was piling up.
![image](https://user-images.githubusercontent.com/61416876/104446667-b1b5cd00-5592-11eb-9187-19e286751f5e.png)
I have discovered that once the Janitor pods are in that state they are piling up. 
![image](https://user-images.githubusercontent.com/61416876/104446851-ee81c400-5592-11eb-81aa-a0824e863442.png)
![image](https://user-images.githubusercontent.com/61416876/104447036-238e1680-5593-11eb-9222-ea227c9b2248.png)

**Comment by dpatel7** [comment]
Reply from Matt C - Please manually work round by using kubectl and issue an appropriate deletion command via the rancher portal kubectl
The issue is noted, workaround and continue

**Comment by MattCavey** [comment]
@dpatel7 please review if this still occurs and close if not

**Comment by dpatel7** [comment]
Haven't seen this issue since then. It was only caused due to credential issue. I am closing this for now.
