### ISSUE TITLE
At end of long running test (8 hours) cluster became unavailable returning 522 errors

### ISSUE THREAD

**Issue by jpoolGW** [filetrust/program-icap#182]
![image](https://user-images.githubusercontent.com/60877176/104750586-35ff8000-574c-11eb-9def-5e6db6010de3.png)

Run test for 8 hour load, in the last half an hour, the test cluster became unavailable, returning 522 errors

**Comment by jpoolGW** [comment]
Attaching jmeter log
[jmeter_15-01-21.zip](https://github.com/filetrust/program-icap/files/5821768/jmeter_15-01-21.zip)

**Comment by NadHodeGW** [comment]
Closing as no longer a issue as confirmed by Jamie
