### ISSUE TITLE
All Rancher clusters unavailable

### ISSUE THREAD

**Issue by jpoolGW** [filetrust/program-icap#183]
![image](https://user-images.githubusercontent.com/60877176/104888247-61f54e00-5964-11eb-87d8-23ef5448cea7.png)

I think this is related to issue #182 https://github.com/filetrust/program-icap/issues/182

**Comment by dpatel7** [comment]
@tasssko North Cluster gone down again now 
![image](https://user-images.githubusercontent.com/61416876/105396577-fb985600-5c17-11eb-817b-62724e787870.png)

**Comment by NadHodeGW** [comment]
Comment from Jamie:
We have only seen this happening subsequently when Codurance delete the clusters. I believe this is what happened on that occasion.
 
We still can't get them to notify us when changes like that are being made

**Comment by NadHodeGW** [comment]
Closing based on comment above
