### ISSUE TITLE
All Rancher Cluster having issue in mvp-service and rebuild pods "Error: Error response from daemon: No command specified"

### ISSUE THREAD

**Issue by dpatel7** [filetrust/program-icap#186]
![2021-01-21_11h53_41](https://user-images.githubusercontent.com/61416876/105352281-9a578f00-5be5-11eb-89d4-260f8610b3e6.png)
![2021-01-21_11h55_13](https://user-images.githubusercontent.com/61416876/105352296-9deb1600-5be5-11eb-9922-59e63cdb178a.png)
![2021-01-21_12h38_11](https://user-images.githubusercontent.com/61416876/105352312-a3e0f700-5be5-11eb-8818-6ba211725732.png)
![2021-01-21_12h38_23](https://user-images.githubusercontent.com/61416876/105352316-a6dbe780-5be5-11eb-95e3-098e3fef558c.png)

**Comment by Kirsten-Osborn** [comment]
@dpatel7 Apparently this problem has been caused by using docker import instead of docker load in the script - the Dockerfile’s CMD and ENTRYPOINT have not been imported, resulting in this error msg. Sylvester is in the process of updating the script and re-running it against the Glasswall registry.

**Comment by dpatel7** [comment]
@Kirsten-Osborn is this require re-deployment?

**Comment by Kirsten-Osborn** [comment]
@dpatel7 We don't think so - we think we can salvage existing clusters by first replacing the broken images in the registry, then terminating and replacing all nodes that currently hold faulty images from the scale sets.

**Comment by Kirsten-Osborn** [comment]
@dpatel7 the team have confirmed this is resolved now so the issue can be closed
