### ISSUE TITLE
Icap Processing: The error: 'Error getting address info for host' is seen on many occasions when submitting files via c-icap client

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/program-icap#191]
This can happen on any endpoint randomly and not sure of the reason

uks qa south:
![2021-01-28_10h36_13.png](https://images.zenhubusercontent.com/5f315efe0e4f4158677aea6e/66c62f5c-548a-494d-8bba-bdfb621f8a0e)

uks-02
![image.png](https://images.zenhubusercontent.com/5f315efe0e4f4158677aea6e/cb2323aa-eb9c-4fd8-a19b-3c16aaca6f2e)

**Comment by BigPeeg** [comment]
Each time I've seen this error I've been on the VPN. Once I disconnect from the VPN, connection has been ok.
Issue has been raised with IT

**Comment by NadHodeGW** [comment]
Retested with few endpoints with & without vpn and it seems more to be throwing the error: 'Failed to initialize ci_connection_t object' when the endpoint is not working.
