### ISSUE TITLE
NCFS Policy Management View

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#226]
https://glasswall.atlassian.net/browse/FEATURE-690

**Comment by asloman** [comment]
NCFS Policy viewable in Management UI. Updates to policy are applied correctly, and are stored in a fileshare.
View in UI:
![2021-02-05_12h27_38](https://user-images.githubusercontent.com/61416937/107033650-872fec00-67ad-11eb-94cd-a1ec82af0f6b.png)
Policy in store (current, all historical are also stored):
![2021-02-05_12h28_00](https://user-images.githubusercontent.com/61416937/107033704-9878f880-67ad-11eb-9629-d7d3dd86d593.png)
