### ISSUE TITLE
Archive Support - Additional formats

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#228]
This is an extension to [Archive Support (Feature-400)](https://glasswall.atlassian.net/browse/FEATURE-400) providing addition formats not originally supplied .

**Comment by GINAGC** [comment]
Matt to add the details on this one, to add list of supportted and not supported files.

**Comment by MattCavey** [comment]
Decision made to not buy the licenses to support RAR & 7zip - ATR to be updated to show this.
