### ISSUE TITLE
Addition of Administration Cluster Transaction Query Aggregator Service

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#229]
https://glasswall.atlassian.net/browse/FEATURE-780

**Comment by asloman** [comment]
Transaction query aggregator has been added and is functional, returns transactions to the transaction history.
Aggregator Pod:
![2021-02-05_14h50_28](https://user-images.githubusercontent.com/61416937/107048982-7ab58e80-67c1-11eb-9cd7-8e299c5908e7.png)
Screenshot of Logs:
![2021-02-05_14h50_51](https://user-images.githubusercontent.com/61416937/107049032-8903aa80-67c1-11eb-94df-1df7fdd60977.png)
