### ISSUE TITLE
Addition of Adaptation Cluster Transaction Querying Service

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#232]
https://glasswall.atlassian.net/browse/FEATURE-779

**Comment by asloman** [comment]
Service has been created and returns correct Transactions from storage account.
Service Pod:
![2021-02-05_13h05_12](https://user-images.githubusercontent.com/61416937/107037289-c6147080-67b2-11eb-8f89-85ff2d127a0e.png)
Log example of Query Service:
![2021-02-05_13h04_40](https://user-images.githubusercontent.com/61416937/107037261-bbf27200-67b2-11eb-8950-a9cf7fb43fa4.png)
