### ISSUE TITLE
Master Content Management Policy Editing - Failure Settings

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#234]
https://glasswall.atlassian.net/browse/FEATURE-581

**Comment by asloman** [comment]
Un-Processable filetypes action can be updated through the management ui and values persist:
![2021-02-05_12h36_37](https://user-images.githubusercontent.com/61416937/107034568-c7dc3500-67ae-11eb-975a-409af7a18886.png)
Glasswall Blocked filetypes action can be updated through the management ui and values persist:
![2021-02-05_12h37_27](https://user-images.githubusercontent.com/61416937/107034636-e5a99a00-67ae-11eb-8f5f-8c9a7467a44d.png)
The Non-compliant File Service Routing URL can be updated through the Management UI and the values persisted:
![2021-02-05_12h37_52](https://user-images.githubusercontent.com/61416937/107034681-f4904c80-67ae-11eb-806c-efbebd63f73a.png)
