### ISSUE TITLE
Master Content Management Policy Editing - CM Switches

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#235]
https://glasswall.atlassian.net/browse/FEATURE-611

**Comment by asloman** [comment]
Content management policy switches are functional and have been added.
These can be used to update the draft policy through the management ui, and the values persist.
![2021-02-05_12h03_42](https://user-images.githubusercontent.com/61416937/107031503-2fdc4c80-67aa-11eb-8115-bfe6dc224d1c.png)
