### ISSUE TITLE
Policy Management View

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#236]
https://glasswall.atlassian.net/browse/FEATURE-546

**Comment by asloman** [comment]
Policy management API created, policy view available in management ui, where users can view historic, current, and draft policies. They can update policy as well. All policies are stored in filestorage.
Api:
![2021-02-05_12h31_03](https://user-images.githubusercontent.com/61416937/107034009-01607080-67ae-11eb-8f15-d4af6a607143.png)
Management ui page:
![2021-02-05_12h31_56](https://user-images.githubusercontent.com/61416937/107034089-20f79900-67ae-11eb-8187-2838f15dca48.png)
File Store:
![2021-02-05_12h28_00](https://user-images.githubusercontent.com/61416937/107034130-2d7bf180-67ae-11eb-9040-1f98038dc139.png)
