### ISSUE TITLE
ICAP Round Trip (Native Architecture)

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/program-icap#239]
https://glasswall.atlassian.net/browse/FEATURE-667

**Comment by asloman** [comment]
When loading a file into the icap service, it is then passed to rebuild and (dependant on policy) a rebuilt file is returned.

https://user-images.githubusercontent.com/61416937/107056807-a38e5180-67ca-11eb-9c60-7abf0d18ec41.mp4
