### ISSUE TITLE
AKS - Update pathway for existing clusters - no data loss.

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#245]
Enhancement 4 adding functionality to earlier Software Deliverables shall support in-place update with no loss of user data or configuration.

**Comment by GINAGC** [comment]
Added as a priority list for Milestone 1, to focus on documentation and video on the update process for the customer.

**Comment by MattCavey** [comment]
@mpigram this is to document how we get from the terraform deployment we show on Tuesday to what we release on Friday. If we can have a clear update document that we can reference as evidence of compliance for this SOW item then that is success
