### ISSUE TITLE
AKS - Add Azure firewall to limit egress traffic

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#246]
Enhancement 4 shall not authorize, attempt, or conduct any outbound internet access. 

Any software components that depend on the internet (licensing, Telemetry, etc.) shall be configurable to disable at install time. 

The software deliverables of Enhancement 4 have not been developed to require outbound access; an Azure firewall can be used to restrict the egress traffic of a cluster. For AKS there are several FQDN’s that would need to be allowed for the base infrastructure to function. 

 

The instructions to implement an Azure Firewall against an AKS cluster & the additional rules AKS requires to operate can be found here: https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic

**Comment by GINAGC** [comment]
This is already documented and should be enough for that. Closing EPIC as agreed on meeting on 05/02/2021.
