### ISSUE TITLE
AKS - Multi-Cluster deployment (Adaptation, Admin, FileDrop)

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#248]
The design documentation shows the ability to have multiple adaptation clusters connection to a single admin cluster meaning centralised control of multiple adaptation cluster policy and transaction data from a single Management UI.

This deployment style is missing from AKS deployment (but contained in Rancher deployment)

**Comment by GINAGC** [comment]
Moved to the group of design decisions made. Rancher deployment is addressing this one.
