### ISSUE TITLE
Provide documentation for updating a cluster without data loss.

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#260]

**Comment by mpigram** [comment]
@MattCavey this can be done for the Terraform side but regarding the chart updates - I need to confirm with @PaulB-GW and the boys in Development that if charts are upgraded and "pruned", is data on those pods retained and carried over to the next pod?

**Comment by mpigram** [comment]
Leaving some links here to keep together

https://github.com/neumanndaniel/terraform/tree/master/modules/aks

**Comment by BigPeeg** [comment]
@mpigram there is no use made of Pod storage. Anything that needs to be persisted is written to the File Share storage.

**Comment by mpigram** [comment]
@BigPeeg Perfect, thanks Paul. I thought this was the case but wanted to be sure.
