### ISSUE TITLE
Can not login to management UI on North Main Cluster 

### ISSUE THREAD

**Issue by dpatel7** [filetrust/program-icap#270]
URL - https://management-ui-neu-main.northeurope.cloudapp.azure.com/login

Manage to Port-forward the identity management service to local port 6088
Run postman script to create user
Received Email confirmation
Create Password reset Token using postman script
Reset the password using Token

When try to login using those details getting error

![2021-02-09_09h17_37.png](https://images.zenhubusercontent.com/5f350346e54324242466f1a8/5275322c-533a-42d8-b854-d58e9b62fe9d)

**Comment by gw-sbirch** [comment]
- Checked logs of Identity management service - could not see traffic

- Error in the page indicates that the server was trying to call localhost:80, which is not the correct path to the identity management service

- Checked config of management-ui - there was no URL set for identity management

**Comment by dpatel7** [comment]
Manage to login after seb deployed the update
