### ISSUE TITLE
Icap Processing-Develop: Error parsing chunks received on file processing

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/program-icap#286]
The error below returns when processing files on the develop endpoint: icap-client-uks-develop.uksouth.cloudapp.azure.com

![2021-02-12_08h04_14.png](https://images.zenhubusercontent.com/5f315efe0e4f4158677aea6e/1bb55f5b-0536-4014-a0c2-0dfd1dbbe391)

**Comment by BigPeeg** [comment]
The ICAP Server pod had a large number of connections. Investigations are on-going under bug #185 . Restarting the pod clears the connections and I've not been able to repeat the reported error.
