### ISSUE TITLE
Main Environment is currently broken

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/program-icap#296]
Files can't be processed on main anymore; 

![2021-02-16_18h18_36.png](https://images.zenhubusercontent.com/5f315efe0e4f4158677aea6e/4106c2c1-8746-446e-81b3-c7437027ee5d)

UI Analytics shows: Error Getting Metrics; 

Looking at the logs i can't see the Icap service, the contents of the icap-adaptation NS is gone

**Comment by mpigram** [comment]
This was caused by merges into main from develop - when HPA's were moved across a line within the ```archive-adaptation-service.yaml``` was left behind causing an error.

**Comment by mpigram** [comment]
Closing this down now as this is not an issue anymore.
