### ISSUE TITLE
Performance Objective Scenario 1 - Office File 100Mb

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#308]
**Scenario:**
Users: 1
File Type: Office File
File Size: 100MB
Time Limit: No time limit

**Acceptance Criteria**
Video of scenario being executed
File used placed in distinct location ready for live demo

**Comment by asloman** [comment]
https://glasswallsolutionsltd.sharepoint.com/:v:/s/ICAPProgram/EbrxKLqJqP1PihsBTjrlTlUBv48g1-BNHSuICKyS4H7wXA?e=VjdWTS
