### ISSUE TITLE
Performance Objective Scenario 2 - 100MB PDF

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#309]
Scenario:
Users: 1
File Type: PDF File
File Size: 100MB
Time Limit: No time limit

Acceptance Criteria
Video of scenario being executed
File used placed in distinct location ready for live demo

**Comment by asloman** [comment]
https://glasswallsolutionsltd.sharepoint.com/:v:/s/ICAPProgram/EQYrxdWzbq1NhMoJoktU-AMBS8KMIalhjg8VSJcVOvsylA?e=hmluZN
