### ISSUE TITLE
Performance Objective Scenario 3 - 1GB

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#310]
Scenario:
Users: 1
File Type: Other Support File Type
File Size: 1GB
Time Limit: No time limit

Acceptance Criteria
Video of scenario being executed
File used placed in distinct location ready for live demo

**Comment by asloman** [comment]
https://glasswallsolutionsltd.sharepoint.com/:v:/s/ICAPProgram/EcxQOlc2WlJItODAK7fuWwkBObeuqqCU0z0H7MtQSQsMfg?e=iIYUQi
