### ISSUE TITLE
Performance Objective Scenario 5 - 1 Hour - Mixed files any size

### ISSUE THREAD

**Issue by MattCavey** [filetrust/program-icap#312]
Scenario:
Users: 1000
File Types; Office, PDF, Image
File Size: N/A
Time Limit: 1 hour

Acceptance Criteria
Video of scenario being executed
Files used placed in distinct location ready for live demo

**Comment by jpoolGW** [comment]
Successful run completed. Video being submitted for editing now
![screencapture-34-242-5-130-3000-d-vGA6xlyMz-scenario5-icap-live-performance-dashboard-2021-03-02-15_09_08](https://user-images.githubusercontent.com/60877176/109668806-6b7bf380-7b69-11eb-84a0-bfc9ea9cc209.png)

**Comment by asloman** [comment]
https://glasswallsolutionsltd.sharepoint.com/:v:/s/ICAPProgram/Eavs8Hf6h_xIug72eQ0VRzsB0Qs6pVIhd-k28O6aIS_SJQ?e=z5F61G
Video completed. Runs at 4x speed to hurry things along
